# Generated by Django 5.1.3 on 2024-12-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
