# Generated by Django 5.1.3 on 2024-12-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_booking_flight_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('PendingState', 'Pending'), ('ConfirmedState', 'Confirmed'), ('CancelledState', 'Cancelled')], default='PendingState', max_length=50),
        ),
    ]
