# Generated by Django 5.1.3 on 2024-12-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_customuser_loyalty_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('PendingState', 'Pending'), ('ConfirmedState', 'Confirmed'), ('CancelledState', 'Cancelled')], default='PendingState', max_length=20),
        ),
    ]
